### ISSUE TITLE
Punch

### ISSUE THREAD

**Issue by mediapolis** [antiSocialNet/antiSocial#100]
- [x] Live update friends feed w/new posts
- [x] utf8 emoji
- [x] animate photo blowup use original
- [x] remove comments expander focus underline
- [x] modal in mobile don't use position fixed
- [x] on post to wall, target user reaction click does not redisplay reaction summary
- [x] on post to wall, target user comment list does not update after post
- [x] hide avatar when modal open
- [x] suppress 'delete' items from newsfeed
- [x] in public and community some posts are 404
- [x] constrained container max height use % of viewport? if not a bit bigger.

**Comment by mediapolis** [comment]
- [ ] upload replace animated gif croaks

```
fs.js:1055
  binding.unlink(pathModule._makeLong(path), req);
          ^

TypeError: path must be a string or Buffer
    at Object.fs.unlink (fs.js:1055:11)
    at /Users/mrhodes/Development/digitopia-social/common/models/Upload.js:31:10
    at /Users/mrhodes/Development/digitopia-social/node_modules/async/dist/async.js:1121:9
    at replenish (/Users/mrhodes/Development/digitopia-social/node_modules/async/dist/async.js:998:17)
    at /Users/mrhodes/Development/digitopia-social/node_modules/async/dist/async.js:1002:9
    at eachOfLimit (/Users/mrhodes/Development/digitopia-social/node_modules/async/dist/async.js:1027:24)
    at /Users/mrhodes/Development/digitopia-social/node_modules/async/dist/async.js:1032:16
    at eachOf (/Users/mrhodes/Development/digitopia-social/node_modules/async/dist/async.js:1103:5)
    at _asyncMap (/Users/mrhodes/Development/digitopia-social/node_modules/async/dist/async.js:1119:5)
    at Object.map (/Users/mrhodes/Development/digitopia-social/node_modules/async/dist/async.js:1108:16)
    at /Users/mrhodes/Development/digitopia-social/common/models/Upload.js:22:11

```
