### ISSUE TITLE
Unable to reset password

### ISSUE THREAD

**Issue by tevans62** [antiSocialNet/antiSocial#262]
### Issue details

In an attempt to test my SMTP configuration, I tried to reset my password via my reverse-proxy docker MAS installation.

The reset failed with:

Unhandled error for request POST /MyUsers/login: Error: login failed
    at /var/app/current/node_modules/loopback/common/models/user.js:251:26
    at /var/app/current/node_modules/loopback-datasource-juggler/lib/dao.js:2176:5
    at /var/app/current/node_modules/loopback-datasource-juggler/lib/dao.js:2111:9
    at /var/app/current/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1012:9
    at /var/app/current/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:359:16
    at iteratorCallback (/var/app/current/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:935:13)
    at /var/app/current/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:843:16
    at /var/app/current/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1009:13
    at buildResult (/var/app/current/node_modules/loopback-datasource-juggler/lib/dao.js:2077:11)
    at /var/app/current/node_modules/loopback-datasource-juggler/lib/dao.js:2091:13
    at doNotify (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at Function.ObserverMixin._notifyBaseObservers (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
    at Function.ObserverMixin.notifyObserversOf (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
Unhandled error for request POST /MyUsers/login: Error: login failed
    at /var/app/current/node_modules/loopback/common/models/user.js:251:26
    at /var/app/current/node_modules/loopback-datasource-juggler/lib/dao.js:2176:5
    at /var/app/current/node_modules/loopback-datasource-juggler/lib/dao.js:2111:9
    at /var/app/current/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1012:9
    at /var/app/current/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:359:16
    at iteratorCallback (/var/app/current/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:935:13)
    at /var/app/current/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:843:16
    at /var/app/current/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1009:13
    at buildResult (/var/app/current/node_modules/loopback-datasource-juggler/lib/dao.js:2077:11)
    at /var/app/current/node_modules/loopback-datasource-juggler/lib/dao.js:2091:13
    at doNotify (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at Function.ObserverMixin._notifyBaseObservers (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
    at Function.ObserverMixin.notifyObserversOf (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
Unhandled error for request POST /MyUsers/login: Error: login failed
    at /var/app/current/node_modules/loopback/common/models/user.js:251:26
    at /var/app/current/node_modules/loopback-datasource-juggler/lib/dao.js:2176:5
    at /var/app/current/node_modules/loopback-datasource-juggler/lib/dao.js:2111:9
    at /var/app/current/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1012:9
    at /var/app/current/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:359:16
    at iteratorCallback (/var/app/current/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:935:13)
    at /var/app/current/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:843:16
    at /var/app/current/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1009:13
    at buildResult (/var/app/current/node_modules/loopback-datasource-juggler/lib/dao.js:2077:11)
    at /var/app/current/node_modules/loopback-datasource-juggler/lib/dao.js:2091:13
    at doNotify (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at Function.ObserverMixin._notifyBaseObservers (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
    at Function.ObserverMixin.notifyObserversOf (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/var/app/current/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
Unhandled error for request POST /MyUsers/reset: Error: Shared class  "MyUser" has no method handling POST /reset
    at restRemoteMethodNotFound (/var/app/current/node_modules/strong-remoting/lib/rest-adapter.js:416:17)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
    at /var/app/current/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:335:12)
    at next (/var/app/current/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/var/app/current/node_modules/express/lib/router/index.js:174:3)
    at router (/var/app/current/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
    at /var/app/current/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:335:12)
    at next (/var/app/current/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/var/app/current/node_modules/body-parser/lib/types/json.js:100:7)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
    at /var/app/current/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:335:12)
    at next (/var/app/current/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/var/app/current/node_modules/body-parser/lib/types/urlencoded.js:82:7)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
Unhandled error for request POST /MyUsers/reset: Error: Shared class  "MyUser" has no method handling POST /reset
    at restRemoteMethodNotFound (/var/app/current/node_modules/strong-remoting/lib/rest-adapter.js:416:17)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
    at /var/app/current/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:335:12)
    at next (/var/app/current/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/var/app/current/node_modules/express/lib/router/index.js:174:3)
    at router (/var/app/current/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
    at /var/app/current/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:335:12)
    at next (/var/app/current/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/var/app/current/node_modules/body-parser/lib/types/json.js:100:7)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
    at /var/app/current/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:335:12)
    at next (/var/app/current/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/var/app/current/node_modules/body-parser/lib/types/urlencoded.js:82:7)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
Unhandled error for request POST /MyUsers/reset: Error: Shared class  "MyUser" has no method handling POST /reset
    at restRemoteMethodNotFound (/var/app/current/node_modules/strong-remoting/lib/rest-adapter.js:416:17)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
    at /var/app/current/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:335:12)
    at next (/var/app/current/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/var/app/current/node_modules/express/lib/router/index.js:174:3)
    at router (/var/app/current/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
    at /var/app/current/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:335:12)
    at next (/var/app/current/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/var/app/current/node_modules/body-parser/lib/types/json.js:100:7)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
    at /var/app/current/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:335:12)
    at next (/var/app/current/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/var/app/current/node_modules/body-parser/lib/types/urlencoded.js:82:7)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
Unhandled error for request POST /MyUsers/reset: Error: Shared class  "MyUser" has no method handling POST /reset
    at restRemoteMethodNotFound (/var/app/current/node_modules/strong-remoting/lib/rest-adapter.js:416:17)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
    at /var/app/current/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:335:12)
    at next (/var/app/current/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/var/app/current/node_modules/express/lib/router/index.js:174:3)
    at router (/var/app/current/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
    at /var/app/current/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:335:12)
    at next (/var/app/current/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/var/app/current/node_modules/body-parser/lib/types/json.js:100:7)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
    at /var/app/current/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:335:12)
    at next (/var/app/current/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/var/app/current/node_modules/body-parser/lib/types/urlencoded.js:82:7)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
Unhandled error for request POST /MyUsers/reset: Error: Shared class  "MyUser" has no method handling POST /reset
    at restRemoteMethodNotFound (/var/app/current/node_modules/strong-remoting/lib/rest-adapter.js:416:17)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
    at /var/app/current/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:335:12)
    at next (/var/app/current/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/var/app/current/node_modules/express/lib/router/index.js:174:3)
    at router (/var/app/current/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
    at /var/app/current/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:335:12)
    at next (/var/app/current/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/var/app/current/node_modules/body-parser/lib/types/json.js:100:7)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
    at /var/app/current/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:335:12)
    at next (/var/app/current/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/var/app/current/node_modules/body-parser/lib/types/urlencoded.js:82:7)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)

### Affected platforms

- [ X] Server Side Issue

or Client Side Browser
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by mediapolis** [comment]
Thanks, pushed to dockerhub
