### ISSUE TITLE
Links not working on Facebook

### ISSUE THREAD

**Issue by jakedfw** [antiSocialNet/antiSocial#384]
### Issue details

Copied links pasted into Facebook generate an error on links from Facebook. 

1. Click on link icon of myAntisocial post
2. Paste link in Facebook post. Preview appears correctly. Post the link. 
3. Click on link after posting
4. Below error appears in browser window:

TypeError
500 Cannot read property '1' of null
TypeError: Cannot read property '1' of null
    at /var/app/current/server/boot/routes-z-endpoints05-post.js:48:25
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/app/current/node_modules/express/lib/router/route.js:137:13)
    at /var/app/current/server/middleware/context-getFriendAccess.js:50:12
    at /var/app/current/node_modules/loopback-datasource-juggler/lib/dao.js:2175:62
    at /var/app/current/node_modules/loopback-datasource-juggler/lib/dao.js:2111:9
    at /var/app/current/node_modules/async/dist/async.js:1140:9
    at /var/app/current/node_modules/async/dist/async.js:473:16
    at eachOfArrayLike (/var/app/current/node_modules/async/dist/async.js:1057:9)
    at eachOf (/var/app/current/node_modules/async/dist/async.js:1117:5)
    at _asyncMap (/var/app/current/node_modules/async/dist/async.js:1133:5)
    at Object.map (/var/app/current/node_modules/async/dist/async.js:1122:16)
    at allCb (/var/app/current/node_modules/loopback-datasource-juggler/lib/dao.js:2025:13)
    at /var/app/current/node_modules/loopback-connector-mongodb/lib/mongodb.js:1161:9
    at result (/var/app/current/node_modules/mongodb/lib/utils.js:414:17)
    at executeCallback (/var/app/current/node_modules/mongodb/lib/utils.js:406:9)
    at handleCallback (/var/app/current/node_modules/mongodb/lib/utils.js:128:55)
    at self.close (/var/app/current/node_modules/mongodb/lib/cursor.js:904:60)
    at handleCallback (/var/app/current/node_modules/mongodb/lib/utils.js:128:55)
    at completeClose (/var/app/current/node_modules/mongodb/lib/cursor.js:1043:14)
    at Cursor.close (/var/app/current/node_modules/mongodb/lib/cursor.js:1056:10)
    at /var/app/current/node_modules/mongodb/lib/cursor.js:904:21

- [ ] Server Side Issue

or Client Side Browser
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ X] Other / Safari

**Comment by mediapolis** [comment]
New link tracker implementation at Facebook.

-[ ] strip tracker from url before processing request
